const enhancedThumbnailStyles = [
  {
    id: "high-impact",
    name: "High Impact Pro",
    backgroundColor: "#FF1A1A",
    fontFamily: "Bebas Neue, sans-serif",
    fontColor: "#FFFFFF",
    backgroundGradient: {
      enabled: true,
      colors: ["#FF1A1A", "#CC0000"],
      direction: "135deg",
    },
    fontShadow: {
      enabled: true,
      color: "#8B0000",
      blur: 8,
      offsetX: 2,
      offsetY: 2,
    },
    textGradient: {
      enabled: true,
      colors: ["#FFD700", "#FFFFFF"],
      direction: "to top",
      // Ensure gradient applies only to text without extra highlight
      backgroundClip: "text",
      webkitBackgroundClip: "text",
    },
    fontOutlineWidth: 1,
    fontOutlineColor: "#8B0000",
    headlineStyle: {
      fontFamily: "Bebas Neue, sans-serif",
      fontSize: 62,
      fontWeight: 900,
      textGradient: {
        enabled: true,
        colors: ["#FFD700", "#FF6B00"],
        direction: "to right",
        backgroundClip: "text",
        webkitBackgroundClip: "text",
      },
    },
    subtitleStyle: {
      fontFamily: "Poppins, sans-serif",
      fontWeight: 700,
      fontColor: "#FFFFFF",
      textGradient: {
        enabled: false,
      },
    },
    badgeStyle: "floating",
    preview: "/styles/high-impact-preview.png",
    description: "Bold reds for viral product launches",
  },
  {
    id: "dark-code",
    name: "Cyber Terminal",
    backgroundColor: "#111827",
    fontFamily: "Space Mono, monospace",
    fontColor: "#00FF9D",
    backgroundGradient: {
      enabled: true,
      colors: ["#000814", "#00172D"],
      direction: "to bottom right",
    },
    fontShadow: {
      enabled: true,
      color: "#00FF9D",
      blur: 15,
      offsetX: 0,
      offsetY: 0,
    },
    textGradient: {
      enabled: true,
      colors: ["#00FF9D", "#00B8FF"],
      direction: "to right",
      backgroundClip: "text",
      webkitBackgroundClip: "text",
    },
    headlineStyle: {
      fontSize: 52,
      fontWeight: 700,
      fontFamily: "Orbitron, sans-serif",
      textGradient: {
        enabled: true,
        colors: ["#00FF9D", "#FFFFFF"],
        direction: "to top",
        backgroundClip: "text",
        webkitBackgroundClip: "text",
      },
    },
    subtitleStyle: {
      fontFamily: "Space Mono, monospace",
      fontWeight: 400,
      fontColor: "#00B8FF",
      textGradient: {
        enabled: false,
      },
    },
    badgeStyle: "hacker",
    preview: "/styles/dark-code-preview.png",
    description: "Neon hacker glow for coding/AI",
  },
  {
    id: "matrix",
    name: "Digital Rain",
    backgroundColor: "#000000",
    fontFamily: "VT323, monospace",
    fontColor: "#00FF00",
    backgroundGradient: {
      enabled: true,
      colors: ["#001000", "#000000"],
      direction: "to bottom",
    },
    fontShadow: {
      enabled: true,
      color: "#00FF00",
      blur: 20,
      offsetX: 0,
      offsetY: 0,
    },
    textGradient: {
      enabled: true,
      colors: ["#00FF00", "#ADFF2F"],
      direction: "to bottom",
      backgroundClip: "text",
      webkitBackgroundClip: "text",
    },
    headlineStyle: {
      fontSize: 58,
      fontWeight: 400,
      fontFamily: "Digital-7, monospace",
      textGradient: {
        enabled: true,
        colors: ["#00FF00", "#FFFFFF"],
        direction: "to right",
        backgroundClip: "text",
        webkitBackgroundClip: "text",
      },
    },
    subtitleStyle: {
      fontFamily: "VT323, monospace",
      fontWeight: 400,
      fontColor: "#ADFF2F",
      textGradient: {
        enabled: false,
      },
    },
    badgeStyle: "scanlines",
    preview: "/styles/matrix-preview.png",
    description: "Classic Matrix code streams",
  },
  {
    id: "ar-dev-brand",
    name: "AR Dev Brand",
    backgroundColor: "#000000",
    backgroundGradient: {
      enabled: true,
      colors: ["#0A192F", "#000000"],
      direction: "to bottom",
    },
    fontFamily: "Poppins, sans-serif",
    fontColor: "#fefffe",
    fontShadow: {
      enabled: false,
      color: "#12a480",
      blur: 10,
      offsetX: 0,
      offsetY: 0,
    },
    fontOutlineWidth: 0,
    fontOutlineColor: "#7ff8cf",
    textGradient: {
      enabled: true,
      colors: ["#12a480", "#7ff8cf"],
      direction: "to right",
      backgroundClip: "text",
      webkitBackgroundClip: "text",
    },
    fontWeight: 700,
    fontSize: 57,
    headlineStyle: {
      fontFamily: "Poppins, sans-serif",
      fontColor: "#fefffe",
      fontWeight: 700,
      textGradient: {
        enabled: true,
        colors: ["#12a480", "#7ff8cf"],
        direction: "to right",
        backgroundClip: "text",
        webkitBackgroundClip: "text",
      },
    },
    subtitleStyle: {
      fontFamily: "Poppins, sans-serif",
      fontColor: "#fefffe",
      fontWeight: 500,
      textGradient: {
        enabled: true,
        colors: ["#12a480", "#7ff8cf"],
        direction: "to right",
        backgroundClip: "text",
        webkitBackgroundClip: "text",
      },
    },
    badgeStyle: "floating",
    preview: "/styles/ar-dev-brand-preview.png",
    description: "Pro coding brand gradients",
  },
];

export default enhancedThumbnailStyles;
